---
- hosts: digitalocean

  vars:
    do_token: "{{ lookup('env','DO_API_KEY') }}"
    droplets:
    - droplet-one

  tasks:

  - name: ensure ssh key exists
    user: >
      name={{ ansible_user_id }}
      generate_ssh_key=yes
      ssh_key_file=.ssh/id_rsa

  - name: ensure key exists at DigitalOcean
    digital_ocean: >
      state=present
      command=ssh
      name=my_ssh_key
      ssh_pub_key={{ lookup('file', '~/.ssh/id_rsa.pub') }}
      api_token={{ do_token }}
    register: my_ssh_key

  - name: ensure droplets exist
    digital_ocean: >
      state=present
      command=droplet
      name={{ item }}
      unique_name=yes
      size_id=512mb
      region_id=sgp1
      image_id=ubuntu-16-04-x64
      ssh_key_ids={{ my_ssh_key.ssh_key.id }}
      api_token={{ do_token }}
    with_items: droplets
    register: droplet_details

  - name: Add new droplets to host group
    add_host: hostname={{ item.droplet.ip_address }} groupname=launched
    with_items: droplet_details.results
    
  - name: Wait for SSH to come up
    wait_for: host={{ item.droplet.ip_address }} port=22 delay=1 timeout=320 state=started
    with_items: '{{droplet_details.results}}'

- hosts: launched
  user: root
  gather_facts: no
  pre_tasks:
    - name: 'install python2'
      raw: sudo apt-get -y install python-simplejson

    - name: Gathering facts
      setup:
  vars_files:
    - vars/main.yml
  roles:
 #   - geerlingguy.firewall
 #   - geerlingguy.mysql
    - geerlingguy.nginx
    - geerlingguy.php
  tasks:
    - shell: wall 'beep'
