---

- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
  - name: Create linode server
    linode:
      api_key: "{{ lookup('env','LIN_API_KEY') }}"
      name: linodeserver
      plan: 1                   #cheapest
      datacenter: 3             #newmark NJ
      distribution: 146         #centos 6.5
      #password: '-AUX-PASSWORD-HERE'
      ssh_pub_key: "{{ lookup('env', 'PUB_KEY') }}"
      wait: yes
      wait_timeout: 300
      state: present
    register: linode

  - name: Adding the new box to the dynamic inventory
    add_host: hostname="{{ linode.instance.ipv4  }}" groupname=linodehosts

  - name: Wait for SSH to come up
    local_action: wait_for host="{{ linode.instance.ipv4 }}" port=22 delay=60 timeout=320 state=started

- name: Cooking the instance....
  hosts: linodehosts
  user: root
  gather_facts: true
  pre_tasks:
     - name: 'install python2'
       raw: sudo apt-get -y install python-simplejson
     - name: 'install git'
       raw: apt-get -y install git
  vars_files:
    - vars/main.yml
  roles:
    - geerlingguy.firewall
    - geerlingguy.mysql
    - geerlingguy.nginx
    - geerlingguy.php
    - geerlingguy.php-mysql
    - geerlingguy.ansible
    - mglaman.wp-cli
  tasks:
    - name: Configure php-fpm pool (if enabled).
      lineinfile:
        dest: "{{ php_fpm_pool_conf_path }}"
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        state: present
      with_items:
        - regexp: '^listen\.allowed_clients.?=.+$'
          line: "listen.backlog = {{ php_listen_backlog }}"
    - shell: echo "net.core.somaxconn=65536" >> /etc/sysctl.conf
    - service: name=nginx state=restarted
    - service: name=php7.0-fpm state=restarted
    - git: repo="https://github.com/WordPress/WordPress.git"
           dest=/root/html
    - git: repo="https://github.com/Greg-Boggs/ansible-deploy.git"
           dest=/root/ansible-deploy
    - shell: ansible-galaxy install -r ansible-deploy/requirements.yml --force
    - shell: ansible-playbook -i ansible-deploy/hosts ansible-deploy/deploy.yml
    - shell: cd /var/www/current/html;wp core config --dbname=wp --dbuser=wp --dbpass=CHANGETHIS --allow-root;
    - shell: cd /var/www/current/html;wp core install --allow-root --url="test.electricdev.net" --title="Electric Dev Test" --admin_user="electric_admin" --admin_password="workstest" --admin_email="me@gregboggs.com"

