---
- src: franklinkim.newrelic
  version: 1.4.0
- src: geerlingguy.blackfire
  version: 1.0.0
- src: geerlingguy.drupal-console
  version: 1.0.7
- src: geerlingguy.drush
  version: 1.1.4
- src: geerlingguy.firewall
  version: 1.3.1
- src: geerlingguy.mysql
  version: 2.4.2
- src: geerlingguy.nginx
  version: 1.9.5
- src: geerlingguy.php
  version: 3.4.1
- src: geerlingguy.php-mysql
  version: 2.0.1
- src: geerlingguy.php-pecl
  version: 1.3.0
- src: geerlingguy.security
  version: 1.4.0
- src: geerlingguy.varnish
  version: 1.8.1
- src: geerlingguy.ansible
  version: 1.2.0
- src: mglaman.wp-cli
